[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

[colors.selection]
text = '#d3c6aa'
background = '#1e2d28'

[colors.cursor]
text = '#2d353b'
cursor = '#a7c080'

[colors.normal]
black   = '#2D353B'
red     = '#dc7763'
green   = '#67c060'
yellow  = '#f0dd6b'
blue    = '#99b66d'
magenta = '#435822'
cyan    = '#A7C080'
white   = '#c4c9bd'

[colors.bright]
black   = '#888b82'
red     = '#ffaf9f'
green   = '#9ce695'
yellow  = '#fff2a5'
blue    = '#bbd397'
magenta = '#e2f9bf'
cyan    = '#f0ffd8'
white   = '#fcfff8'
